### ISSUE TITLE
Quoted numbers are converted to int types in interpolation, then fail to parse 

### ISSUE THREAD

**Issue by lox** [docker/libcompose#113]
Given:

```
sample:
  image: amazon/amazon-ecs-sample
  environment:
    test_int_as_string:  "100"
```

The result is a panic:

```
panic: interface conversion: interface is int64, not string [recovered]
	panic: interface conversion: interface is int64, not string

goroutine 1 [running]:
github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml.recovery(0xc82016e728)
	/Users/lachlan/.go/src/github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml/decode.go:83 +0xb4
github.com/docker/libcompose/project.(*MaporEqualSlice).UnmarshalYAML(0xc8201b6418, 0x600690, 0x15, 0x4123a0, 0xc8201911a0, 0x0, 0x0)
	/Users/lachlan/.go/src/github.com/docker/libcompose/project/types_yaml.go:190 +0x4cc
github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).mapping.func1(0xfa4fc8, 0xc8201b6418, 0xc82016df50, 0xc820185500)
	/Users/lachlan/.go/src/github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml/decode.go:385 +0x81
github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).mapping(0xc820185500, 0x411460, 0xc8201dc340, 0xd4)
	/Users/lachlan/.go/src/github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml/decode.go:396 +0x29f
github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).parse(0xc820185500, 0x505ee0, 0xc8201b6418, 0xd9)
	/Users/lachlan/.go/src/github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml/decode.go:206 +0x852
github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).mappingStruct(0xc820185500, 0x5894e0, 0xc8201b6300, 0xd9)
	/Users/lachlan/.go/src/github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml/decode.go:493 +0x503
github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).mapping(0xc820185500, 0x5894e0, 0xc8201b6300, 0xd9)
	/Users/lachlan/.go/src/github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml/decode.go:402 +0x790
github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).parse(0xc820185500, 0x3eda00, 0xc8201b6300, 0x16)
	/Users/lachlan/.go/src/github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml/decode.go:206 +0x852
github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).document(0xc820185500, 0x3eda00, 0xc8201b6300, 0x16)
	/Users/lachlan/.go/src/github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml/decode.go:182 +0x19a
github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml.(*Decoder).Decode(0xc820185500, 0x3eda00, 0xc8201b6300, 0x0, 0x0)
	/Users/lachlan/.go/src/github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml/decode.go:133 +0x27a
github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml.Unmarshal(0xc8201a64e0, 0xc1, 0xc1, 0x3eda00, 0xc8201b6300, 0x0, 0x0)
	/Users/lachlan/.go/src/github.com/docker/libcompose/vendor/github.com/cloudfoundry-incubator/candiedyaml/decode.go:102 +0xf5
github.com/docker/libcompose/utils.Convert(0x4a86c0, 0xc820190b40, 0x3eda00, 0xc8201b6300, 0x0, 0x0)
	/Users/lachlan/.go/src/github.com/docker/libcompose/utils/util.go:66 +0xcc
github.com/docker/libcompose/project.readEnvFile(0xfa4ca8, 0x884698, 0x7fff5fbff959, 0x26, 0xc820190b40, 0x4177a0, 0x0, 0x0)
	/Users/lachlan/.go/src/github.com/docker/libcompose/project/merge.go:76 +0x9e
github.com/docker/libcompose/project.parse(0xfa4ca8, 0x884698, 0xfa4cd0, 0x884698, 0x7fff5fbff959, 0x26, 0xc820190b40, 0xc820190a80, 0xc8200a38c0, 0x0, ...)
	/Users/lachlan/.go/src/github.com/docker/libcompose/project/merge.go:158 +0x79
github.com/docker/libcompose/project.mergeProject(0xc8200b1400, 0xc820184e00, 0x102, 0x302, 0xc82016f0f8, 0x0, 0x0)
	/Users/lachlan/.go/src/github.com/docker/libcompose/project/merge.go:47 +0x300
github.com/docker/libcompose/project.(*Project).Load(0xc8200b1400, 0xc820184e00, 0x102, 0x302, 0x0, 0x0)
	/Users/lachlan/.go/src/github.com/docker/libcompose/project/project.go:127 +0xf6
github.com/docker/libcompose/project.(*Project).Parse(0xc8200b1400, 0x0, 0x0)
	/Users/lachlan/.go/src/github.com/docker/libcompose/project/project.go:73 +0x148
github.com/docker/libcompose/docker.NewProject(0xc8200ba540, 0xc8200ba540, 0x0, 0x0)
	/Users/lachlan/.go/src/github.com/docker/libcompose/docker/project.go:40 +0x3b3
github.com/99designs/ecs-cli/compose.TransformComposeFile(0x7fff5fbff959, 0x26, 0x7fff5fbff951, 0x4, 0x1, 0x0, 0x0)
	/Users/lachlan/Projects/99designs/go/src/github.com/99designs/ecs-cli/compose/transform.go:26 +0x251
main.main()
	/Users/lachlan/Projects/99designs/go/src/github.com/99designs/ecs-cli/cli/ecs-compose-task/main.go:23 +0x183
```

**Comment by dnephin** [comment]
This is being worked on in #108

**Comment by lox** [comment]
It seems like that PR is just going to return an error rather than panic. The bug seems like it's lower down the stack. I'm not sure why the quoted integer is being passed by the YAML library is an int64, it should be a string.

**Comment by dnephin** [comment]
Oops, I glossed over this too quickly. You're right, that PR is maybe not related.

**Comment by joshwget** [comment]
I just took a look at this, and it definitely seems to be a result of #86. @ibuildthecloud, it looks like that approach had an unexpected bug.

**Comment by joshwget** [comment]
I don't think this issue is present anymore. #174 should have fixed it.

**Comment by vdemeester** [comment]
@joshwget yep, tried it out, it is working :+1:
