### ISSUE TITLE
fails on empty root level volume

### ISSUE THREAD

**Issue by surajssd** [docker/libcompose#430]
Using following docker-compose.yml

```yaml
$ cat docker-compose.yml 
version: '2'
services:
  db:
    image: sandbox-psql
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
```

fails as:
```bash
$ libcompose up
WARN[0000] Note: This is an experimental alternate implementation of the Compose CLI (https://github.com/docker/compose) 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4da737]

goroutine 1 [running]:
panic(0x86e7e0, 0xc420010160)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/docker/libcompose/vendor/github.com/urfave/cli.HandleAction.func1(0xc420195cc8)
        /home/hummer/go/src/github.com/docker/libcompose/vendor/github.com/urfave/cli/app.go:472 +0x29e
panic(0x86e7e0, 0xc420010160)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/docker/libcompose/project.(*Project).handleVolumeConfig(0xc420092620)
        /home/hummer/go/src/github.com/docker/libcompose/project/project.go:319 +0x1d7
github.com/docker/libcompose/project.(*Project).load(0xc420092620, 0x8f663a, 0x12, 0xc4202a1680, 0x7a, 0x27a, 0xc420195620, 0x4125e8)
        /home/hummer/go/src/github.com/docker/libcompose/project/project.go:235 +0x3a0
github.com/docker/libcompose/project.(*Project).Parse(0xc420092620, 0xd36ee0, 0xc4202f4300)
        /home/hummer/go/src/github.com/docker/libcompose/project/project.go:112 +0x15a
github.com/docker/libcompose/docker.NewProject(0xc4200ce870, 0x0, 0x0, 0x0, 0x18, 0xc420195810)
        /home/hummer/go/src/github.com/docker/libcompose/docker/project.go:58 +0x106
github.com/docker/libcompose/cli/docker/app.(*ProjectFactory).Create(0xd70ec0, 0xc4202c6500, 0x0, 0x8, 0x8, 0xc4202c2d20)
        /home/hummer/go/src/github.com/docker/libcompose/cli/docker/app/factory.go:20 +0xae
github.com/docker/libcompose/cli/app.WithProject.func1(0xc4202c6500, 0x0, 0x0)
        /home/hummer/go/src/github.com/docker/libcompose/cli/app/app.go:45 +0x4e
reflect.Value.call(0x852ec0, 0xc4202c24c0, 0x13, 0x8f0050, 0x4, 0xc420195c68, 0x1, 0x1, 0x471c88, 0x8e2120, ...)
        /usr/local/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x852ec0, 0xc4202c24c0, 0x13, 0xc420195c68, 0x1, 0x1, 0x0, 0x140, 0x140)
        /usr/local/go/src/reflect/value.go:302 +0xa4
github.com/docker/libcompose/vendor/github.com/urfave/cli.HandleAction(0x852ec0, 0xc4202c24c0, 0xc4202c6500, 0x0, 0x0)
        /home/hummer/go/src/github.com/docker/libcompose/vendor/github.com/urfave/cli/app.go:481 +0x1e0
github.com/docker/libcompose/vendor/github.com/urfave/cli.Command.Run(0x8efc34, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8f7e6e, 0x15, 0x0, ...)
        /home/hummer/go/src/github.com/docker/libcompose/vendor/github.com/urfave/cli/command.go:186 +0xc26
github.com/docker/libcompose/vendor/github.com/urfave/cli.(*App).Run(0xc4202b6180, 0xc42000c6a0, 0x2, 0x2, 0x0, 0x0)
        /home/hummer/go/src/github.com/docker/libcompose/vendor/github.com/urfave/cli/app.go:235 +0x60c
main.main()
        /home/hummer/go/src/github.com/docker/libcompose/cli/main/main.go:75 +0x16d4
```

but works with docker-compose.

**Comment by mikeifomin** [comment]
In my case the error has gone

**Comment by cdrage** [comment]
I think this can be closed :)
